/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:15c5f977-7f3b-44af-9083-94d80d53fbaf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aDWR7oFG9",
    "aws_user_pools_web_client_id": "7tqbrbvajg06369repvqipb3au",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://j3ezehkk5bcjxacjsx2rxn3ady.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
